name: First Workflow
on: workflow_dispatch # manually trigger this workflow
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: Multi-Line Shell Commands
        run: |
          echo "First output"
          echo "Second output"
      - name: Pring goodbye
        run: echo "Done - bye!"
